<?php
echo '<h2 class="bambora_redirect">'.$data["headerText"].'</h2>';
echo '<h3 class="bambora_redirect">'.$data["headerText2"].'</h3>';
echo '<script type="text/javascript">
  (function (n, t, i, r, u, f, e) { n[u] = n[u] || function() {
  (n[u].q = n[u].q || []).push(arguments)}; f = t.createElement(i);
  e = t.getElementsByTagName(i)[0]; f.async = 1; f.src = r; e.parentNode.insertBefore(f, e)
  })(window, document, "script","'.$data["paymentWindowUrl"].'", "bam");

  var onClose = function(){
    window.location.href = "'.$data["cancelUrl"].'";
  };

  var options = {
    "windowstate": 2,
    "onClose": onClose
  }
  
  bam("open", "'.$data["bamboraCheckoutUrl"].'", options);

</script>';
?>